[package]
name = "firesquare-web-api"
version = "0.1.0"
description = "Firesquare launcher UI"
authors = ["Egor Ternovoy <cofob@riseup.net>"]
edition = "2021"
rust-version = "1.57"

[dependencies]
firesquare-structs = { path = "../firesquare-structs" }
