name: CI

on:
  push:
  pull_request:

env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: full
  PACKAGES: gnome-devel libadwaita-1-dev

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sfackler/actions/rustup@master
      - run: cargo fmt --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get update
          sudo apt-get install -y $PACKAGES
      - uses: sfackler/actions/rustup@master
      - run: echo "::set-output name=version::$(rustc --version)"
        id: rust-version
      - uses: Swatinem/rust-cache@v2
        with:
          key: "clippy"
      - run: cargo clippy --all --all-targets

  # windows:
  #   name: windows
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: sfackler/actions/rustup@master
  #     - run: echo "::set-output name=version::$(rustc --version)"
  #       id: rust-version
  #     - uses: actions/cache@v3
  #       with:
  #         path: ~/.cargo
  #         key: cargo-${{ runner.os }}-${{ steps.rust-version.outputs.version }}-${{ hashFiles('Cargo.lock') }}
  #         restore-keys: |
  #           cargo-${{ runner.os }}-${{ steps.rust-version.outputs.version }}-
  #           cargo-${{ runner.os }}-
  #     - uses: actions/cache@v3
  #       with:
  #         path: target
  #         key: target-${{ github.job }}-${{ steps.rust-version.outputs.version }}-${{ hashFiles('Cargo.lock') }}
  #         restore-keys: |
  #           cargo-${{ runner.os }}-${{ steps.rust-version.outputs.version }}-
  #           cargo-${{ runner.os }}-
  #     - run: cargo test
  #     - run: cargo build --release
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: windows
  #         path: target/release/firesquare-launcher.exe

  linux:
    name: linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sfackler/actions/rustup@master
      - run: echo "::set-output name=version::$(rustc --version)"
        id: rust-version
      - run: rustup target add x86_64-unknown-linux-gnu
      - run: |
          sudo apt-get update
          sudo apt-get install -y $PACKAGES
      - uses: Swatinem/rust-cache@v2
        with:
          key: "linux"
      - run: cargo test --target x86_64-unknown-linux-gnu
      - run: cargo build --target x86_64-unknown-linux-gnu --release
      - uses: actions/upload-artifact@v3
        with:
          name: linux
          path: target/x86_64-unknown-linux-gnu/release/firesquare-launcher
